CREATE TABLE DFW_properties (
    Unique_id INT PRIMARY KEY,
    Latitude DECIMAL(10, 7),
    Longitude DECIMAL(10, 7),
    Price_Per_Unit VARCHAR(255),
    Percent_1_Bed FLOAT,
    Percent_2_Bed FLOAT,
    Percent_3_Bed FLOAT,
    Percent_4_Bed FLOAT,
    Percent_Studios FLOAT,
    Affordable_Type VARCHAR(255),
    Amenities VARCHAR(255),
    Anchor_GLA VARCHAR(255),
    Anchor_Tenants VARCHAR(255),
    Architect_Name VARCHAR(255),
    Average_Weighted_Rent FLOAT,
    Avg_Asking_Bed VARCHAR(255),
    Avg_Asking_SF VARCHAR(255),
    Avg_Asking_Unit VARCHAR(255),
    Avg_Concessions_Percent FLOAT,
    Avg_Effective_SF VARCHAR(255),
    Avg_Effective_Unit VARCHAR(255),
    Avg_Rent_Direct_Industrial VARCHAR(255),
    Avg_Rent_Direct_Office VARCHAR(255),
    Avg_Rent_Direct_Retail VARCHAR(255),
    Avg_Rent_Sublet_Industrial FLOAT,
    Avg_Rent_Sublet_Office FLOAT,
    Avg_Rent_Sublet_Retail FLOAT,
    Avg_Unit_SF DECIMAL(10, 2),
    Building_Class CHAR,
    Building_Operating_Expenses VARCHAR(255),
    Building_Park VARCHAR(255),
    Building_Status VARCHAR(255),
    Building_Tax_Expenses VARCHAR(255),
    Cap_Rate VARCHAR(255),
    Ceiling_Height VARCHAR(255),
    City VARCHAR(255),
    Closest_Transit_Stop VARCHAR(255),
    Closest_Transit_Stop_Dist DECIMAL(10, 2),
    Closest_Transit_Stop_Walk_Time INT,
    Column_Spacing VARCHAR(255),
    Construction_Material VARCHAR(255),
    Core_Factor VARCHAR(255),
    County_Name VARCHAR(255),
    Cross_Street VARCHAR(255),
    Days_On_Market INT,
    Developer_Name VARCHAR(255),
    Direct_Available_Space VARCHAR(255),
    Direct_Services VARCHAR(255),
    Direct_Vacant_Space DECIMAL(10, 2),
    Drive_Ins VARCHAR(255),
    Energy_Star VARCHAR(255),
    Exp_Year INT,
    Features VARCHAR(1000),
    For_Sale_Price DECIMAL(10, 2),
    For_Sale_Status CHAR,
    Four_Bedroom_Asking_Rent_Bed VARCHAR(255),
    Four_Bedroom_Asking_Rent_SF VARCHAR(255),
    Four_Bedroom_Asking_Rent_Unit VARCHAR(255),
    Four_Bedroom_Avg_SF VARCHAR(255),
    Four_Bedroom_Concessions_Percent DECIMAL(10, 2),
    Four_Bedroom_Effective_Rent_Bed VARCHAR(255),
    Four_Bedroom_Effective_Rent_SF VARCHAR(255),
    Four_Bedroom_Effective_Rent_Unit VARCHAR(255),
    Four_Bedroom_Vacancy_Percent DECIMAL(10, 2),
    Four_Bedroom_Vacant_Units INT,
    Gas VARCHAR(255),
    Heating VARCHAR(255),
    Land_Area_AC DECIMAL(10, 2),
    Land_Area_SF DECIMAL(10, 2),
    Last_Sale_Date DECIMAL(10, 2),
    Last_Sale_Price DECIMAL(10, 2),
    Leasing_Company_Address VARCHAR(255),
    Leasing_Company_City_State_Zip VARCHAR(255),
    Leasing_Company_Contact VARCHAR(255),
    Leasing_Company_Fax VARCHAR(10),
    Leasing_Company_Name VARCHAR(255),
    Leasing_Company_Phone VARCHAR(10),
    LEED_Certified VARCHAR(255),
    Market_Name VARCHAR(255),
    Market_Segment VARCHAR(255),
    Max_Building_Contiguous_Space DECIMAL(10, 2),
    Max_Floor_Contiguous_Space DECIMAL(10, 2),
    Number_Of_1_Bedrooms_Units INT,
    Number_Of_2_Bedrooms_Units INT,
    Number_Of_3_Bedrooms_Units INT,
    Number_Of_4_Bedrooms_Units INT,
    Number_Of_Beds INT,
    Number_Of_Cranes INT,
    Number_Of_Elevators INT,
    Number_Of_Loading_Docks INT,
    Number_Of_Parking_Spaces INT,
    Rooms INT,
    Number_Of_Stories INT,
    Number_Of_Studios_Units INT,
    Number_Of_Units INT,
    Office_Space DECIMAL(10, 2),
    One_Bedroom_Asking_Rent_Bed VARCHAR(255),
    One_Bedroom_Asking_Rent_SF VARCHAR(255),
    One_Bedroom_Asking_Rent_Unit VARCHAR(255),
    One_Bedroom_Avg_SF VARCHAR(255),
    One_Bedroom_Concessions_Percent DECIMAL(10, 2),
    One_Bedroom_Effective_Rent_Bed VARCHAR(255),
    One_Bedroom_Effective_Rent_SF VARCHAR(255),
    One_Bedroom_Effective_Rent_Unit VARCHAR(255),
    One_Bedroom_Vacancy_Percent DECIMAL(10, 2),
    One_Bedroom_Vacant_Units INT,
    Ops_Expense VARCHAR(255),
    Ops_Expense_Per_SF VARCHAR(255),
    Owner_Address VARCHAR(255),
    Owner_City_State_Zip VARCHAR(255),
    Owner_Contact VARCHAR(255),
    Owner_Name VARCHAR(255),
    Owner_Phone VARCHAR(10),
    Parcel_Number_1 VARCHAR(255),
    Parcel_Number_2 VARCHAR(255),
    Parking_Ratio DECIMAL(10, 2),
    Parking_Spaces_Per_Unit DECIMAL(10, 2),
    Percent_Leased DECIMAL(10, 2),
    Power VARCHAR(255),
    Pre_Leasing VARCHAR(255),
    Primary_Agent_Name VARCHAR(255),
    Property_Address VARCHAR(255),
    Property_Location VARCHAR(255),
    Property_Manager_Address VARCHAR(255),
    Property_Manager_City_State_Zip VARCHAR(255),
    Property_Manager_Contact VARCHAR(255),
    Property_Manager_Name VARCHAR(255),
    Property_Manager_Phone VARCHAR(255),
    Property_Name VARCHAR(255),
    PropertyID VARCHAR(255),
    PropertyType VARCHAR(255),
    Proposed_Land_Use VARCHAR(255),
    Rail_Lines VARCHAR(255),
    Recorded_Owner_Address VARCHAR(255),
    Recorded_Owner_City_State_Zip VARCHAR(255),
    Recorded_Owner_Contact VARCHAR(255),
    Recorded_Owner_Name VARCHAR(255),
    Recorded_Owner_Phone VARCHAR(10),
    Rent_Type VARCHAR(255),
    Rent_Per_SF_Yr VARCHAR(255),
    RBA VARCHAR(255),
    Sale_Company_Address VARCHAR(255),
    Sale_Company_City_State_Zip VARCHAR(255),
    Sale_Company_Contact VARCHAR(255),
    Sale_Company_Fax VARCHAR(255),
    Sale_Company_Name VARCHAR(255),
    Sale_Company_Phone VARCHAR(255),
    Sales_Company VARCHAR(255),
    Sales_Contact VARCHAR(255),
    Sales_Contact_Phone VARCHAR(255),
    Secondary_Type VARCHAR(255),
    Services VARCHAR(255),
    Sewer VARCHAR(255),
    Smallest_Available_Space DECIMAL(10, 2),
    Sprinklers VARCHAR(255),
    Star_Rating INT,
    State VARCHAR(255),
    Studio_Asking_Rent_Bed VARCHAR(255),
    Studio_Asking_Rent_SF VARCHAR(255),
    Studio_Asking_Rent_Unit VARCHAR(255),
    Studio_Avg_SF VARCHAR(255),
    Studio_Concessions_Percent DECIMAL(10, 2),
    Studio_Effective_Rent_Bed VARCHAR(255),
    Studio_Effective_Rent_SF VARCHAR(255),
    Studio_Effective_Rent_Unit VARCHAR(255),
    Studio_Vacancy_Percent DECIMAL(10, 2),
    Studio_Vacant_Units INT,
    Style VARCHAR(255),
    Sublet_Available_Space DECIMAL(10, 2),
    Sublet_Services VARCHAR(255),
    Sublet_Vacant_Space DECIMAL(10, 2),
    Submarket_Cluster VARCHAR(255),
    Submarket_Name VARCHAR(255),
    Tax_Year INT,
    Taxes_Per_SF DECIMAL(10, 2),
    Taxes_Total DECIMAL(10, 2),
    Tenancy VARCHAR(255),
    Three_Bedroom_Asking_Rent_Bed VARCHAR(255),
    Three_Bedroom_Asking_Rent_SF VARCHAR(255),
    Three_Bedroom_Asking_Rent_Unit VARCHAR(255),
    Three_Bedroom_Avg_SF VARCHAR(255),
    Three_Bedroom_Concessions_Percent DECIMAL(10, 2),
    Three_Bedroom_Effective_Rent_Bed VARCHAR(255),
    Three_Bedroom_Effective_Rent_SF VARCHAR(255),
    Three_Bedroom_Effective_Rent_Unit VARCHAR(255),
    Three_Bedroom_Vacancy_Percent DECIMAL(10, 2),
    Three_Bedroom_Vacant_Units INT,
    Total_Available_Space_SF DECIMAL(10, 2),
    Total_Buildings DECIMAL(10, 2),
    Total_New_Space_SF DECIMAL(10, 2),
    Total_Relet_Space_SF DECIMAL(10, 2),
    Total_Sublet_Space_SF DECIMAL(10, 2),
    Total_Vacant_Avail_Relet_Space_SF DECIMAL(10, 2),
    Total_Vacant_Avail_Sublet_Space_SF DECIMAL(10, 2),
    Total_Vacant_Available DECIMAL(10, 2),
    True_Owner_Address DECIMAL(10, 2),
    True_Owner_City_State_Zip VARCHAR(255),
    True_Owner_Contact VARCHAR(255),
    True_Owner_Name VARCHAR(255),
    True_Owner_Phone VARCHAR(10),
    Two_Bedroom_Asking_Rent_Per_Bed VARCHAR(255),
    Two_Bedroom_Asking_Rent_Per_SF VARCHAR(255),
    Two_Bedroom_Asking_Rent_Per_Unit VARCHAR(255),
    Two_Bedroom_Avg_SF VARCHAR(255),
    Two_Bedroom_Concessions_Percent DECIMAL(10,2),
    Two_Bedroom_Effective_Rent_Per_Bed VARCHAR(255),
    Two_Bedroom_Effective_Rent_Per_SF VARCHAR(255),
    Two_Bedroom_Effective_Rent_Per_Unit VARCHAR(255),
    Two_Bedroom_Vacancy_Percent DECIMAL(10,2),
    Two_Bedroom_Vacant_Units INT,
    Typical_Floor_Size DECIMAL(10,2),
    University VARCHAR(255),
    Vacancy_Percent DECIMAL,
    Water VARCHAR(255),
    Year_Built INT,
    Year_Renovated INT,
    Zip VARCHAR(255),
    Zoning VARCHAR(255),
    Population_2022_1m INT,
    Pop_Grwth_2022_2027_1m_Percent DECIMAL(10,2),
    Pop_Grwth_2022_2027_3m_Percent DECIMAL(10,2),
    Population_2022_3m INT,
    Pop_Grwth_2022_2027_5m_Percent DECIMAL(10,2),
    Population_2022_5m INT
)
